/*

 ROOM_TILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 37 x 28
   Tile set      : C:\Users\mjbai\Downloads\gbtd22\background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define room_tilemapWidth 37
#define room_tilemapHeight 28
#define room_tilemapBank 0

extern unsigned char room_tilemap[];

/* End of ROOM_TILEMAP.H */
